spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.101:8848
    alicloud:
      access-key: LTAI5tNTLHEkrFujRxSqBzzu
      secret-key: vkdNA7b7uj6O11HaEZz279T0hDYkeo
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-oos-zyl

  application:
    name: gulimall-third-party

server:
  port: 30000
