server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.101:8848


  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.150.101:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.150.101
    port: 6379
    password: 123321
  cache:
    type: redis # 使用redis作为缓存
    redis:
      time-to-live: 3600s # 过期时间
      # key-prefix: CACHE_ # 会导致自己在@Cacheable里设置的名字失效，所以这里不指定
      use-key-prefix: true # key值加前缀
      cache-null-values: true # 缓存控制
  session:
    store-type: redis

mybatis-plus:
  #  扫描依赖的jar包下的所有mapper.xml
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 开启feign熔断，开启后能够监控到远程调用资源
feign:
  sentinel:
    enabled: true
# 审计模块暴露，应用健康情况（配合sentinel dashboard）
management:
  endpoints:
    web:
      exposure:
        exclude: '*'

# 开启日志
logging:
  level:
    com.atguigu.gulimall: debug
    # feign调用日志，链路日志
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10